### ISSUE TITLE
Adding editheme to .Rprofile

### ISSUE THREAD

**Issue by jgarces02** [fkeck/editheme#1]
Hi @fkeck, I found this package very useful, thanks!

Do you know any way to adding it to the .Rprofile? Because I'm trying to add it but an extra window pops out an plots are drawn here, not in RStudio panels (and if I close it, it's necessary run again `set_base_sty("Idle Fingers")`)

Here is my code in the .Rprofile:
```
library(editheme)
set_base_sty("Idle Fingers") #this name according your global appearance
```
![image](https://user-images.githubusercontent.com/27858969/34869266-a289c420-f786-11e7-8378-bf31e210ed91.png)

**Comment by fkeck** [comment]
Hi, I'm afraid this is not possible. I could be wrong but I think Rprofile is executed before RStudio initialize its own graphical device.
So the best you can do is to load editheme in your Rprofile but you have to set the theme manually during your session with:

    set_base_sty()

**Comment by jgarces02** [comment]
What's a pity! Thanks anyway!

**Comment by jgarces02** [comment]
Hi again @fkeck, 

I had an idea, it's a bit tricky but it works! You can add a custom function to your .Rprofile that automatically cleans the plot panel and runs `set_base_sty()`, something like that:
```
## Clean plot panel and re-configure editheme
.env$cplot <- function(){
  dev.off()
  set_base_sty("Idle Fingers")
}
```

**Comment by fkeck** [comment]
Nice!
