### ISSUE TITLE
Non-CRAN packages dependencies in DESCRIPTION

### ISSUE THREAD

**Issue by choisy** [fkeck/editheme#3]
No need to do a pull request for that I guess, but in the DESCRIPTION file, you should add the following line:

Remotes: ropenscilabs/styles

This will manage neatly the dependency to the styles package that is not on CRAN: no need anymore to manually pre-install the styles package before installing your editheme package as you recommend to do in the README.

**Comment by fkeck** [comment]
Thanks! I did not know that.
